#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose
  - git

# Configure system settings required by SonarQube's Elasticsearch (Elasticsearch needs these)
sysctl:
  vm.max_map_count: 262144

runcmd:
  # Install Docker and grant permissions
  - usermod -aG docker ubuntu
  - systemctl start docker
  - systemctl enable docker
  
  # Clone your repository (REPLACE YOUR_REPO)
  - git clone https://github.com/YOUR_USER/YOUR_REPO.git /home/ubuntu/sonar
  - chown -R ubuntu:ubuntu /home/ubuntu/sonar

  # Run the SonarQube stack using the dedicated docker-compose file
  - su - ubuntu -c "cd /home/ubuntu/sonar && docker-compose -f docker-compose-sonar.yml pull"
  - su - ubuntu -c "cd /home/ubuntu/sonar && docker-compose -f docker-compose-sonar.yml up -d"
